#ifndef BOARD_DEFINES_H
#define BOARD_DEFINES_H


// rgb led defines
#define LED_PORT GPIO_PORTF_BASE
#define LED_PWM_BASE PWM1_BASE
#define LED_PWM_PERIPH SYSCTL_PERIPH_PWM1
#define LED_PERIPH SYSCTL_PERIPH_GPIOF

#define RED_LED_PINMUX GPIO_PF1_M1PWM5
#define RED_LED_PIN GPIO_PIN_1
#define RED_LED_GEN PWM_GEN_2
#define RED_LED_OUT PWM_OUT_5
#define RED_LED_OUT_BIT PWM_OUT_5_BIT

#define GREEN_LED_PINMUX GPIO_PF3_M1PWM7
#define GREEN_LED_PIN GPIO_PIN_3
#define GREEN_LED_GEN PWM_GEN_3
#define GREEN_LED_OUT PWM_OUT_7
#define GREEN_LED_OUT_BIT PWM_OUT_7_BIT
// #define RED_LED_PORT GPIO_PORTF_BASE

#define M_PWM_PERIOD 999

// M1 defines
#define M1_PORT GPIO_PORTD_BASE
// PWM
#define M1_PWM_BASE PWM1_BASE
#define M1_PWM_PERIPH SYSCTL_PERIPH_PWM1
#define M1_PWM_PINMUX GPIO_PD0_M1PWM0
#define M1_PWM_PIN GPIO_PIN_0
#define M1_PWM_GEN PWM_GEN_0
#define M1_PWM_OUT PWM_OUT_0
#define M1_PWM_OUT_BIT PWM_OUT_0_BIT
// GPIO
#define M1_IN_PERIPH SYSCTL_PERIPH_GPIOD
#define M1_IN1_PIN GPIO_PIN_1
#define M1_IN2_PIN GPIO_PIN_2

// M2 defines
#define M2_PORT GPIO_PORTB_BASE
// PWM
#define M2_PWM_BASE PWM0_BASE
#define M2_PWM_PERIPH SYSCTL_PERIPH_PWM0
#define M2_PWM_PINMUX GPIO_PB4_M0PWM2
#define M2_PWM_PIN GPIO_PIN_4
#define M2_PWM_GEN PWM_GEN_1
#define M2_PWM_OUT PWM_OUT_2
#define M2_PWM_OUT_BIT PWM_OUT_2_BIT
// GPIO
#define M2_IN_PERIPH SYSCTL_PERIPH_GPIOB
#define M2_IN1_PIN GPIO_PIN_0
#define M2_IN2_PIN GPIO_PIN_1

// Robot defines
// #define ENC_PPR (380*4*7)
#define ENC_PPR 1496
#define WHEEL_RADIUS (0.065 / 2)
#define BASE_L 0.17

// encoder 1
#define ENC1_PERIPH SYSCTL_PERIPH_QEI1
#define ENC1_PINS_PERIPH SYSCTL_PERIPH_GPIOC
#define ENC1_BASE QEI1_BASE
#define ENC1_GPIO_BASE GPIO_PORTC_BASE
#define ENC1_A_PINMUX GPIO_PC5_PHA1
#define ENC1_B_PINMUX GPIO_PC6_PHB1
#define ENC1_A_PIN GPIO_PIN_5
#define ENC1_B_PIN GPIO_PIN_6

// encoder 2
#define ENC2_PERIPH SYSCTL_PERIPH_QEI0
#define ENC2_PINS_PERIPH SYSCTL_PERIPH_GPIOD
#define ENC2_BASE QEI0_BASE
#define ENC2_GPIO_BASE GPIO_PORTD_BASE
#define ENC2_A_PINMUX GPIO_PD6_PHA0
#define ENC2_B_PINMUX GPIO_PD7_PHB0
#define ENC2_A_PIN GPIO_PIN_6
#define ENC2_B_PIN GPIO_PIN_7

// timer period
#define CPU_FREQ 80000000
#define SAMPLE_RATE_HZ 80     // sample rate in ms
#define DELTA_T (1.0 / SAMPLE_RATE_HZ)
#define DELTA_T_MS (1000 / SAMPLE_RATE_HZ)

#define MAX_PWM 1000.0
#define MIN_PWM -1000.0


#define LOOP_TIMER_PERIOD ((CPU_FREQ/SAMPLE_RATE_HZ)-1)

#endif